### ISSUE TITLE
Create a static app for tonglec.org

### ISSUE THREAD

**Issue by dc-tonglec** [TongLeC/TLCEdu#1]
### 🚀**Overview of the feature request**

Create a static app for tonglec.org

### **Tasks to do**
- [x] Design & create the app infrastructure, the app should support English, Simplified & Traditional Chinese
- [x] Simplified Chinese should be translated to Traditional Chinese by code
- [x] Work with the Teaching team to add content.

### **Time logging**
| Date | Hours |
| :--: | :---: |
