### ISSUE TITLE
Modify home page content

### ISSUE THREAD

**Issue by jia-rong-lu** [TongLeC/TLCEdu#14]
### **Tasks to do**

- [x] 首页大部分内容的白色背景去掉
- [x] 首页适配排版问题
- [x] 同乐书籍和网上读经机增加内容
- [x] 题目显示适配换行
- [x] 添加同乐整体教育理论内容

### **Time logging**
| Date | Hours |
| :--: | :---: |
|05/27 | 5h |
|05/30 | 5.5h |

**Comment by jia-rong-lu** [comment]
- [ ] 首页的大图，请做成两边不留白。 
- [ ] 首页大部图的底部，请加一个“标题栏，有背景颜色的”，
- [ ] 网页上所有的图片按钮，请采用“圆角”, 也是体现中国文化中的处世哲学。
- [ ] 首页上所有的图标的排列和展示，不要用上下滚动的滚动条，要改为左右（横向）的滚动条。 
- [ ] 所有分享资源的标题，请采用黑色字体，并且居中。旁边的“阅读更多”，挪到最右边对齐。

**Comment by jia-rong-lu** [comment]
**06/01 home page**

- [ ] 导航栏小bug修改
![image](https://user-images.githubusercontent.com/104044848/171315044-9f3dac60-11fa-4a04-b320-474b75b210bd.png)
- [ ] 导航栏的菜单字体，请加粗 (Bold).  
- [ ] 这个分割条的字体，请加粗。而且关于语言学习法，全称是 “同乐语言学习法“，因为那是我们自己创新了很多理念，理论，实践，融合在里面的一套完整的方法。 
- [ ] 包括菜单的地方，也是统一“同乐语言学习法”“同乐整体教育理论”。
- [ ] 导航栏的菜单的下滑菜单，把每一行做个阴影，显示出是不同的小标题。
- [ ] 读经机的图标，看起来，左上角的“同乐教育”篆章好像缺了一点。请确认是否有必要让清心老师重新调整左上角的Logo位置，重新截图。 
- [ ] 原创文章部分，只有三篇，看起来跟上面的资源数量相比，比较单薄，请增加到5篇。 
- [ ] 首页每一部分都增加相应的描述
- [ ] 首页增加区域区分部分，稍微明显一些。参考：socrative.com 

- [ ] 这个分割条的字体，位置调整到居中，旁边的“点点点”，放到右边。-- Good to have. 
- [ ] 这两首诗的字体，可以略大一点，行间距也大一点，基本占满我画的那个黄色的框框。主要是希望跟右边的排版，看起来左右匀称。-- Good to have.

**Comment by jia-rong-lu** [comment]
06/02

- [ ] 首页各种资源的分享的标题，请加粗。 
- [ ] 网上读经机，增加两项： GK诗词朗诵 、G1诗词朗诵

**Comment by QingqinKong** [comment]
- [ ] 目录的数量不一致
- [ ] 点击导航栏时有报错
- [ ] 点击导航栏二级目录 Active没有变

1. 目录的数量不一致
![1da7893c-5c0c-4569-a38f-a9224aeabab3](https://user-images.githubusercontent.com/101536317/172275453-f1ae2f4f-5893-40f0-b03b-137a19c21e9c.jpg)

![e6540b8f-e382-46ac-83b6-21fcd76cba0d](https://user-images.githubusercontent.com/101536317/172275427-a7333c99-d6ff-4c99-b213-626cb74c7ddc.jpg)

2. 点击导航栏时有报错
![075040c0-0676-4491-96ba-637abf6c2eb5](https://user-images.githubusercontent.com/101536317/172275489-e58ec445-76e5-4d58-82bb-f3aecf42b21b.jpg)

3.点击导航栏二级目录 Active没有变
![2e94e370-0605-466f-8827-6a206ceaeacc](https://user-images.githubusercontent.com/101536317/172275532-5c61bf7d-62fd-4743-b465-552165e25186.jpg)
